// *** WARNING: this file was generated by the Kulado Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package containerservice

import (
	"github.com/pkg/errors"
	"github.com/kulado/kulado/sdk/go/kulado"
)

// Manages an Azure Container Registry.
// 
// > **Note:** All arguments including the access key will be stored in the raw state as plain-text.
// [Read more about sensitive data in state](https://www.terraform.io/docs/state/sensitive-data.html).
//
// > This content is derived from https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/website/docs/r/container_registry.html.markdown.
type Registry struct {
	s *kulado.ResourceState
}

// NewRegistry registers a new resource with the given unique name, arguments, and options.
func NewRegistry(ctx *kulado.Context,
	name string, args *RegistryArgs, opts ...kulado.ResourceOpt) (*Registry, error) {
	if args == nil || args.ResourceGroupName == nil {
		return nil, errors.New("missing required argument 'ResourceGroupName'")
	}
	inputs := make(map[string]interface{})
	if args == nil {
		inputs["adminEnabled"] = nil
		inputs["georeplicationLocations"] = nil
		inputs["location"] = nil
		inputs["name"] = nil
		inputs["resourceGroupName"] = nil
		inputs["sku"] = nil
		inputs["storageAccount"] = nil
		inputs["storageAccountId"] = nil
		inputs["tags"] = nil
	} else {
		inputs["adminEnabled"] = args.AdminEnabled
		inputs["georeplicationLocations"] = args.GeoreplicationLocations
		inputs["location"] = args.Location
		inputs["name"] = args.Name
		inputs["resourceGroupName"] = args.ResourceGroupName
		inputs["sku"] = args.Sku
		inputs["storageAccount"] = args.StorageAccount
		inputs["storageAccountId"] = args.StorageAccountId
		inputs["tags"] = args.Tags
	}
	inputs["adminPassword"] = nil
	inputs["adminUsername"] = nil
	inputs["loginServer"] = nil
	s, err := ctx.RegisterResource("azure:containerservice/registry:Registry", name, true, inputs, opts...)
	if err != nil {
		return nil, err
	}
	return &Registry{s: s}, nil
}

// GetRegistry gets an existing Registry resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetRegistry(ctx *kulado.Context,
	name string, id kulado.ID, state *RegistryState, opts ...kulado.ResourceOpt) (*Registry, error) {
	inputs := make(map[string]interface{})
	if state != nil {
		inputs["adminEnabled"] = state.AdminEnabled
		inputs["adminPassword"] = state.AdminPassword
		inputs["adminUsername"] = state.AdminUsername
		inputs["georeplicationLocations"] = state.GeoreplicationLocations
		inputs["location"] = state.Location
		inputs["loginServer"] = state.LoginServer
		inputs["name"] = state.Name
		inputs["resourceGroupName"] = state.ResourceGroupName
		inputs["sku"] = state.Sku
		inputs["storageAccount"] = state.StorageAccount
		inputs["storageAccountId"] = state.StorageAccountId
		inputs["tags"] = state.Tags
	}
	s, err := ctx.ReadResource("azure:containerservice/registry:Registry", name, id, inputs, opts...)
	if err != nil {
		return nil, err
	}
	return &Registry{s: s}, nil
}

// URN is this resource's unique name assigned by Kulado.
func (r *Registry) URN() *kulado.URNOutput {
	return r.s.URN()
}

// ID is this resource's unique identifier assigned by its provider.
func (r *Registry) ID() *kulado.IDOutput {
	return r.s.ID()
}

// Specifies whether the admin user is enabled. Defaults to `false`.
func (r *Registry) AdminEnabled() *kulado.BoolOutput {
	return (*kulado.BoolOutput)(r.s.State["adminEnabled"])
}

// The Password associated with the Container Registry Admin account - if the admin account is enabled.
func (r *Registry) AdminPassword() *kulado.StringOutput {
	return (*kulado.StringOutput)(r.s.State["adminPassword"])
}

// The Username associated with the Container Registry Admin account - if the admin account is enabled.
func (r *Registry) AdminUsername() *kulado.StringOutput {
	return (*kulado.StringOutput)(r.s.State["adminUsername"])
}

// A list of Azure locations where the container registry should be geo-replicated.
func (r *Registry) GeoreplicationLocations() *kulado.ArrayOutput {
	return (*kulado.ArrayOutput)(r.s.State["georeplicationLocations"])
}

// Specifies the supported Azure location where the resource exists. Changing this forces a new resource to be created.
func (r *Registry) Location() *kulado.StringOutput {
	return (*kulado.StringOutput)(r.s.State["location"])
}

// The URL that can be used to log into the container registry.
func (r *Registry) LoginServer() *kulado.StringOutput {
	return (*kulado.StringOutput)(r.s.State["loginServer"])
}

// Specifies the name of the Container Registry. Changing this forces a new resource to be created.
func (r *Registry) Name() *kulado.StringOutput {
	return (*kulado.StringOutput)(r.s.State["name"])
}

// The name of the resource group in which to create the Container Registry. Changing this forces a new resource to be created.
func (r *Registry) ResourceGroupName() *kulado.StringOutput {
	return (*kulado.StringOutput)(r.s.State["resourceGroupName"])
}

// The SKU name of the the container registry. Possible values are `Classic` (which was previously `Basic`), `Basic`, `Standard` and `Premium`.
func (r *Registry) Sku() *kulado.StringOutput {
	return (*kulado.StringOutput)(r.s.State["sku"])
}

func (r *Registry) StorageAccount() *kulado.Output {
	return r.s.State["storageAccount"]
}

// The ID of a Storage Account which must be located in the same Azure Region as the Container Registry.
func (r *Registry) StorageAccountId() *kulado.StringOutput {
	return (*kulado.StringOutput)(r.s.State["storageAccountId"])
}

// A mapping of tags to assign to the resource.
func (r *Registry) Tags() *kulado.MapOutput {
	return (*kulado.MapOutput)(r.s.State["tags"])
}

// Input properties used for looking up and filtering Registry resources.
type RegistryState struct {
	// Specifies whether the admin user is enabled. Defaults to `false`.
	AdminEnabled interface{}
	// The Password associated with the Container Registry Admin account - if the admin account is enabled.
	AdminPassword interface{}
	// The Username associated with the Container Registry Admin account - if the admin account is enabled.
	AdminUsername interface{}
	// A list of Azure locations where the container registry should be geo-replicated.
	GeoreplicationLocations interface{}
	// Specifies the supported Azure location where the resource exists. Changing this forces a new resource to be created.
	Location interface{}
	// The URL that can be used to log into the container registry.
	LoginServer interface{}
	// Specifies the name of the Container Registry. Changing this forces a new resource to be created.
	Name interface{}
	// The name of the resource group in which to create the Container Registry. Changing this forces a new resource to be created.
	ResourceGroupName interface{}
	// The SKU name of the the container registry. Possible values are `Classic` (which was previously `Basic`), `Basic`, `Standard` and `Premium`.
	Sku interface{}
	StorageAccount interface{}
	// The ID of a Storage Account which must be located in the same Azure Region as the Container Registry.
	StorageAccountId interface{}
	// A mapping of tags to assign to the resource.
	Tags interface{}
}

// The set of arguments for constructing a Registry resource.
type RegistryArgs struct {
	// Specifies whether the admin user is enabled. Defaults to `false`.
	AdminEnabled interface{}
	// A list of Azure locations where the container registry should be geo-replicated.
	GeoreplicationLocations interface{}
	// Specifies the supported Azure location where the resource exists. Changing this forces a new resource to be created.
	Location interface{}
	// Specifies the name of the Container Registry. Changing this forces a new resource to be created.
	Name interface{}
	// The name of the resource group in which to create the Container Registry. Changing this forces a new resource to be created.
	ResourceGroupName interface{}
	// The SKU name of the the container registry. Possible values are `Classic` (which was previously `Basic`), `Basic`, `Standard` and `Premium`.
	Sku interface{}
	StorageAccount interface{}
	// The ID of a Storage Account which must be located in the same Azure Region as the Container Registry.
	StorageAccountId interface{}
	// A mapping of tags to assign to the resource.
	Tags interface{}
}
