// *** WARNING: this file was generated by the Kulado Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as kulado from "@kulado/kulado";
import * as utilities from "../utilities";

/**
 * Manages a CosmosDB (formally DocumentDB) Account.
 * 
 * ## Example Usage
 * 
 * ```typescript
 * import * as kulado from "@kulado/kulado";
 * import * as azure from "@kulado/azure";
 * import * as random from "@kulado/random";
 * 
 * const rg = new azure.core.ResourceGroup("rg", {
 *     location: var_resource_group_location,
 *     name: var_resource_group_name,
 * });
 * const ri = new random.RandomInteger("ri", {
 *     max: 99999,
 *     min: 10000,
 * });
 * const db = new azure.cosmosdb.Account("db", {
 *     consistencyPolicy: {
 *         consistencyLevel: "BoundedStaleness",
 *         maxIntervalInSeconds: 10,
 *         maxStalenessPrefix: 200,
 *     },
 *     enableAutomaticFailover: true,
 *     geoLocations: [
 *         {
 *             failoverPriority: 1,
 *             location: var_failover_location,
 *         },
 *         {
 *             failoverPriority: 0,
 *             location: rg.location,
 *             prefix: kulado.interpolate`tfex-cosmos-db-${ri.result}-customid`,
 *         },
 *     ],
 *     kind: "GlobalDocumentDB",
 *     location: rg.location,
 *     name: kulado.interpolate`tfex-cosmos-db-${ri.result}`,
 *     offerType: "Standard",
 *     resourceGroupName: rg.name,
 * });
 * ```
 *
 * > This content is derived from https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/website/docs/r/cosmosdb_account.html.markdown.
 */
export class Account extends kulado.CustomResource {
    /**
     * Get an existing Account resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     */
    public static get(name: string, id: kulado.Input<kulado.ID>, state?: AccountState, opts?: kulado.CustomResourceOptions): Account {
        return new Account(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __kuladoType = 'azure:cosmosdb/account:Account';

    /**
     * Returns true if the given object is an instance of Account.  This is designed to work even
     * when multiple copies of the Kulado SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Account {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__kuladoType'] === Account.__kuladoType;
    }

    /**
     * The capabilities which should be enabled for this Cosmos DB account. Possible values are `EnableAggregationPipeline`, `EnableCassandra`, `EnableGremlin`, `EnableTable`, `MongoDBv3.4`, and `mongoEnableDocLevelTTL`.
     */
    public readonly capabilities!: kulado.Output<{ name: string }[] | undefined>;
    /**
     * A list of connection strings available for this CosmosDB account. If the kind is `GlobalDocumentDB`, this will be empty.
     */
    public /*out*/ readonly connectionStrings!: kulado.Output<string[]>;
    /**
     * Specifies a `consistency_policy` resource, used to define the consistency policy for this CosmosDB account.
     */
    public readonly consistencyPolicy!: kulado.Output<{ consistencyLevel: string, maxIntervalInSeconds?: number, maxStalenessPrefix?: number }>;
    /**
     * Enable automatic fail over for this Cosmos DB account.
     */
    public readonly enableAutomaticFailover!: kulado.Output<boolean | undefined>;
    /**
     * Enable multi-master support for this Cosmos DB account.
     */
    public readonly enableMultipleWriteLocations!: kulado.Output<boolean | undefined>;
    /**
     * The endpoint used to connect to the CosmosDB account.
     */
    public /*out*/ readonly endpoint!: kulado.Output<string>;
    public readonly failoverPolicies!: kulado.Output<{ id: string, location: string, priority: number }[] | undefined>;
    /**
     * Specifies a `geo_location` resource, used to define where data should be replicated with the `failover_priority` 0 specifying the primary location.
     */
    public readonly geoLocations!: kulado.Output<{ failoverPriority: number, id: string, location: string, prefix?: string }[]>;
    /**
     * CosmosDB Firewall Support: This value specifies the set of IP addresses or IP address ranges in CIDR form to be included as the allowed list of client IP's for a given database account. IP addresses/ranges must be comma separated and must not contain any spaces.
     */
    public readonly ipRangeFilter!: kulado.Output<string | undefined>;
    /**
     * Enables virtual network filtering for this Cosmos DB account.
     */
    public readonly isVirtualNetworkFilterEnabled!: kulado.Output<boolean | undefined>;
    /**
     * Specifies the Kind of CosmosDB to create - possible values are `GlobalDocumentDB` and `MongoDB`. Defaults to `GlobalDocumentDB`. Changing this forces a new resource to be created.
     */
    public readonly kind!: kulado.Output<string | undefined>;
    /**
     * The name of the Azure region to host replicated data.
     */
    public readonly location!: kulado.Output<string>;
    /**
     * The capability to enable - Possible values are `EnableTable`, `EnableCassandra`, and `EnableGremlin`.
     */
    public readonly name!: kulado.Output<string>;
    /**
     * Specifies the Offer Type to use for this CosmosDB Account - currently this can only be set to `Standard`.
     */
    public readonly offerType!: kulado.Output<string>;
    /**
     * The Primary master key for the CosmosDB Account.
     */
    public /*out*/ readonly primaryMasterKey!: kulado.Output<string>;
    /**
     * The Primary read-only master Key for the CosmosDB Account.
     */
    public /*out*/ readonly primaryReadonlyMasterKey!: kulado.Output<string>;
    /**
     * A list of read endpoints available for this CosmosDB account.
     */
    public /*out*/ readonly readEndpoints!: kulado.Output<string[]>;
    /**
     * The name of the resource group in which the CosmosDB Account is created. Changing this forces a new resource to be created.
     */
    public readonly resourceGroupName!: kulado.Output<string>;
    /**
     * The Secondary master key for the CosmosDB Account.
     */
    public /*out*/ readonly secondaryMasterKey!: kulado.Output<string>;
    /**
     * The Secondary read-only master key for the CosmosDB Account.
     */
    public /*out*/ readonly secondaryReadonlyMasterKey!: kulado.Output<string>;
    /**
     * A mapping of tags to assign to the resource.
     */
    public readonly tags!: kulado.Output<{[key: string]: any}>;
    /**
     * Specifies a `virtual_network_rules` resource, used to define which subnets are allowed to access this CosmosDB account.
     */
    public readonly virtualNetworkRules!: kulado.Output<{ id: string }[] | undefined>;
    /**
     * A list of write endpoints available for this CosmosDB account.
     */
    public /*out*/ readonly writeEndpoints!: kulado.Output<string[]>;

    /**
     * Create a Account resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: AccountArgs, opts?: kulado.CustomResourceOptions)
    constructor(name: string, argsOrState?: AccountArgs | AccountState, opts?: kulado.CustomResourceOptions) {
        let inputs: kulado.Inputs = {};
        if (opts && opts.id) {
            const state = argsOrState as AccountState | undefined;
            inputs["capabilities"] = state ? state.capabilities : undefined;
            inputs["connectionStrings"] = state ? state.connectionStrings : undefined;
            inputs["consistencyPolicy"] = state ? state.consistencyPolicy : undefined;
            inputs["enableAutomaticFailover"] = state ? state.enableAutomaticFailover : undefined;
            inputs["enableMultipleWriteLocations"] = state ? state.enableMultipleWriteLocations : undefined;
            inputs["endpoint"] = state ? state.endpoint : undefined;
            inputs["failoverPolicies"] = state ? state.failoverPolicies : undefined;
            inputs["geoLocations"] = state ? state.geoLocations : undefined;
            inputs["ipRangeFilter"] = state ? state.ipRangeFilter : undefined;
            inputs["isVirtualNetworkFilterEnabled"] = state ? state.isVirtualNetworkFilterEnabled : undefined;
            inputs["kind"] = state ? state.kind : undefined;
            inputs["location"] = state ? state.location : undefined;
            inputs["name"] = state ? state.name : undefined;
            inputs["offerType"] = state ? state.offerType : undefined;
            inputs["primaryMasterKey"] = state ? state.primaryMasterKey : undefined;
            inputs["primaryReadonlyMasterKey"] = state ? state.primaryReadonlyMasterKey : undefined;
            inputs["readEndpoints"] = state ? state.readEndpoints : undefined;
            inputs["resourceGroupName"] = state ? state.resourceGroupName : undefined;
            inputs["secondaryMasterKey"] = state ? state.secondaryMasterKey : undefined;
            inputs["secondaryReadonlyMasterKey"] = state ? state.secondaryReadonlyMasterKey : undefined;
            inputs["tags"] = state ? state.tags : undefined;
            inputs["virtualNetworkRules"] = state ? state.virtualNetworkRules : undefined;
            inputs["writeEndpoints"] = state ? state.writeEndpoints : undefined;
        } else {
            const args = argsOrState as AccountArgs | undefined;
            if (!args || args.consistencyPolicy === undefined) {
                throw new Error("Missing required property 'consistencyPolicy'");
            }
            if (!args || args.offerType === undefined) {
                throw new Error("Missing required property 'offerType'");
            }
            if (!args || args.resourceGroupName === undefined) {
                throw new Error("Missing required property 'resourceGroupName'");
            }
            inputs["capabilities"] = args ? args.capabilities : undefined;
            inputs["consistencyPolicy"] = args ? args.consistencyPolicy : undefined;
            inputs["enableAutomaticFailover"] = args ? args.enableAutomaticFailover : undefined;
            inputs["enableMultipleWriteLocations"] = args ? args.enableMultipleWriteLocations : undefined;
            inputs["failoverPolicies"] = args ? args.failoverPolicies : undefined;
            inputs["geoLocations"] = args ? args.geoLocations : undefined;
            inputs["ipRangeFilter"] = args ? args.ipRangeFilter : undefined;
            inputs["isVirtualNetworkFilterEnabled"] = args ? args.isVirtualNetworkFilterEnabled : undefined;
            inputs["kind"] = args ? args.kind : undefined;
            inputs["location"] = args ? args.location : undefined;
            inputs["name"] = args ? args.name : undefined;
            inputs["offerType"] = args ? args.offerType : undefined;
            inputs["resourceGroupName"] = args ? args.resourceGroupName : undefined;
            inputs["tags"] = args ? args.tags : undefined;
            inputs["virtualNetworkRules"] = args ? args.virtualNetworkRules : undefined;
            inputs["connectionStrings"] = undefined /*out*/;
            inputs["endpoint"] = undefined /*out*/;
            inputs["primaryMasterKey"] = undefined /*out*/;
            inputs["primaryReadonlyMasterKey"] = undefined /*out*/;
            inputs["readEndpoints"] = undefined /*out*/;
            inputs["secondaryMasterKey"] = undefined /*out*/;
            inputs["secondaryReadonlyMasterKey"] = undefined /*out*/;
            inputs["writeEndpoints"] = undefined /*out*/;
        }
        super(Account.__kuladoType, name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Account resources.
 */
export interface AccountState {
    /**
     * The capabilities which should be enabled for this Cosmos DB account. Possible values are `EnableAggregationPipeline`, `EnableCassandra`, `EnableGremlin`, `EnableTable`, `MongoDBv3.4`, and `mongoEnableDocLevelTTL`.
     */
    readonly capabilities?: kulado.Input<kulado.Input<{ name: kulado.Input<string> }>[]>;
    /**
     * A list of connection strings available for this CosmosDB account. If the kind is `GlobalDocumentDB`, this will be empty.
     */
    readonly connectionStrings?: kulado.Input<kulado.Input<string>[]>;
    /**
     * Specifies a `consistency_policy` resource, used to define the consistency policy for this CosmosDB account.
     */
    readonly consistencyPolicy?: kulado.Input<{ consistencyLevel: kulado.Input<string>, maxIntervalInSeconds?: kulado.Input<number>, maxStalenessPrefix?: kulado.Input<number> }>;
    /**
     * Enable automatic fail over for this Cosmos DB account.
     */
    readonly enableAutomaticFailover?: kulado.Input<boolean>;
    /**
     * Enable multi-master support for this Cosmos DB account.
     */
    readonly enableMultipleWriteLocations?: kulado.Input<boolean>;
    /**
     * The endpoint used to connect to the CosmosDB account.
     */
    readonly endpoint?: kulado.Input<string>;
    readonly failoverPolicies?: kulado.Input<kulado.Input<{ id?: kulado.Input<string>, location: kulado.Input<string>, priority: kulado.Input<number> }>[]>;
    /**
     * Specifies a `geo_location` resource, used to define where data should be replicated with the `failover_priority` 0 specifying the primary location.
     */
    readonly geoLocations?: kulado.Input<kulado.Input<{ failoverPriority: kulado.Input<number>, id?: kulado.Input<string>, location: kulado.Input<string>, prefix?: kulado.Input<string> }>[]>;
    /**
     * CosmosDB Firewall Support: This value specifies the set of IP addresses or IP address ranges in CIDR form to be included as the allowed list of client IP's for a given database account. IP addresses/ranges must be comma separated and must not contain any spaces.
     */
    readonly ipRangeFilter?: kulado.Input<string>;
    /**
     * Enables virtual network filtering for this Cosmos DB account.
     */
    readonly isVirtualNetworkFilterEnabled?: kulado.Input<boolean>;
    /**
     * Specifies the Kind of CosmosDB to create - possible values are `GlobalDocumentDB` and `MongoDB`. Defaults to `GlobalDocumentDB`. Changing this forces a new resource to be created.
     */
    readonly kind?: kulado.Input<string>;
    /**
     * The name of the Azure region to host replicated data.
     */
    readonly location?: kulado.Input<string>;
    /**
     * The capability to enable - Possible values are `EnableTable`, `EnableCassandra`, and `EnableGremlin`.
     */
    readonly name?: kulado.Input<string>;
    /**
     * Specifies the Offer Type to use for this CosmosDB Account - currently this can only be set to `Standard`.
     */
    readonly offerType?: kulado.Input<string>;
    /**
     * The Primary master key for the CosmosDB Account.
     */
    readonly primaryMasterKey?: kulado.Input<string>;
    /**
     * The Primary read-only master Key for the CosmosDB Account.
     */
    readonly primaryReadonlyMasterKey?: kulado.Input<string>;
    /**
     * A list of read endpoints available for this CosmosDB account.
     */
    readonly readEndpoints?: kulado.Input<kulado.Input<string>[]>;
    /**
     * The name of the resource group in which the CosmosDB Account is created. Changing this forces a new resource to be created.
     */
    readonly resourceGroupName?: kulado.Input<string>;
    /**
     * The Secondary master key for the CosmosDB Account.
     */
    readonly secondaryMasterKey?: kulado.Input<string>;
    /**
     * The Secondary read-only master key for the CosmosDB Account.
     */
    readonly secondaryReadonlyMasterKey?: kulado.Input<string>;
    /**
     * A mapping of tags to assign to the resource.
     */
    readonly tags?: kulado.Input<{[key: string]: any}>;
    /**
     * Specifies a `virtual_network_rules` resource, used to define which subnets are allowed to access this CosmosDB account.
     */
    readonly virtualNetworkRules?: kulado.Input<kulado.Input<{ id: kulado.Input<string> }>[]>;
    /**
     * A list of write endpoints available for this CosmosDB account.
     */
    readonly writeEndpoints?: kulado.Input<kulado.Input<string>[]>;
}

/**
 * The set of arguments for constructing a Account resource.
 */
export interface AccountArgs {
    /**
     * The capabilities which should be enabled for this Cosmos DB account. Possible values are `EnableAggregationPipeline`, `EnableCassandra`, `EnableGremlin`, `EnableTable`, `MongoDBv3.4`, and `mongoEnableDocLevelTTL`.
     */
    readonly capabilities?: kulado.Input<kulado.Input<{ name: kulado.Input<string> }>[]>;
    /**
     * Specifies a `consistency_policy` resource, used to define the consistency policy for this CosmosDB account.
     */
    readonly consistencyPolicy: kulado.Input<{ consistencyLevel: kulado.Input<string>, maxIntervalInSeconds?: kulado.Input<number>, maxStalenessPrefix?: kulado.Input<number> }>;
    /**
     * Enable automatic fail over for this Cosmos DB account.
     */
    readonly enableAutomaticFailover?: kulado.Input<boolean>;
    /**
     * Enable multi-master support for this Cosmos DB account.
     */
    readonly enableMultipleWriteLocations?: kulado.Input<boolean>;
    readonly failoverPolicies?: kulado.Input<kulado.Input<{ id?: kulado.Input<string>, location: kulado.Input<string>, priority: kulado.Input<number> }>[]>;
    /**
     * Specifies a `geo_location` resource, used to define where data should be replicated with the `failover_priority` 0 specifying the primary location.
     */
    readonly geoLocations?: kulado.Input<kulado.Input<{ failoverPriority: kulado.Input<number>, id?: kulado.Input<string>, location: kulado.Input<string>, prefix?: kulado.Input<string> }>[]>;
    /**
     * CosmosDB Firewall Support: This value specifies the set of IP addresses or IP address ranges in CIDR form to be included as the allowed list of client IP's for a given database account. IP addresses/ranges must be comma separated and must not contain any spaces.
     */
    readonly ipRangeFilter?: kulado.Input<string>;
    /**
     * Enables virtual network filtering for this Cosmos DB account.
     */
    readonly isVirtualNetworkFilterEnabled?: kulado.Input<boolean>;
    /**
     * Specifies the Kind of CosmosDB to create - possible values are `GlobalDocumentDB` and `MongoDB`. Defaults to `GlobalDocumentDB`. Changing this forces a new resource to be created.
     */
    readonly kind?: kulado.Input<string>;
    /**
     * The name of the Azure region to host replicated data.
     */
    readonly location?: kulado.Input<string>;
    /**
     * The capability to enable - Possible values are `EnableTable`, `EnableCassandra`, and `EnableGremlin`.
     */
    readonly name?: kulado.Input<string>;
    /**
     * Specifies the Offer Type to use for this CosmosDB Account - currently this can only be set to `Standard`.
     */
    readonly offerType: kulado.Input<string>;
    /**
     * The name of the resource group in which the CosmosDB Account is created. Changing this forces a new resource to be created.
     */
    readonly resourceGroupName: kulado.Input<string>;
    /**
     * A mapping of tags to assign to the resource.
     */
    readonly tags?: kulado.Input<{[key: string]: any}>;
    /**
     * Specifies a `virtual_network_rules` resource, used to define which subnets are allowed to access this CosmosDB account.
     */
    readonly virtualNetworkRules?: kulado.Input<kulado.Input<{ id: kulado.Input<string> }>[]>;
}
