// *** WARNING: this file was generated by the Kulado Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as kulado from "@kulado/kulado";
import * as utilities from "../utilities";

/**
 * Manages a Mongo Collection within a Cosmos DB Account.
 * 
 * ## Example Usage
 * 
 * ```typescript
 * import * as kulado from "@kulado/kulado";
 * import * as azure from "@kulado/azure";
 * 
 * const exampleAccount = kulado.output(azure.cosmosdb.getAccount({
 *     name: "tfex-cosmosdb-account",
 *     resourceGroupName: "tfex-cosmosdb-account-rg",
 * }));
 * const exampleMongoCollection = new azure.cosmosdb.MongoCollection("example", {
 *     accountName: exampleAccount.name,
 *     databaseName: exampleAccount.name,
 *     defaultTtlSeconds: 777,
 *     indexes: [
 *         {
 *             key: "aKey",
 *             unique: false,
 *         },
 *         {
 *             key: "uniqueKey",
 *             unique: true,
 *         },
 *     ],
 *     name: "tfex-cosmos-mongo-db",
 *     resourceGroupName: exampleAccount.resourceGroupName,
 *     shardKey: "uniqueKey",
 * });
 * const exampleMongoDatabase = new azure.cosmosdb.MongoDatabase("example", {
 *     accountName: exampleAccount.name,
 *     name: "tfex-cosmos-mongo-db",
 *     resourceGroupName: exampleAccount.resourceGroupName,
 * });
 * ```
 *
 * > This content is derived from https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/website/docs/r/cosmosdb_mongo_collection.html.markdown.
 */
export class MongoCollection extends kulado.CustomResource {
    /**
     * Get an existing MongoCollection resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     */
    public static get(name: string, id: kulado.Input<kulado.ID>, state?: MongoCollectionState, opts?: kulado.CustomResourceOptions): MongoCollection {
        return new MongoCollection(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __kuladoType = 'azure:cosmosdb/mongoCollection:MongoCollection';

    /**
     * Returns true if the given object is an instance of MongoCollection.  This is designed to work even
     * when multiple copies of the Kulado SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is MongoCollection {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__kuladoType'] === MongoCollection.__kuladoType;
    }

    public readonly accountName!: kulado.Output<string>;
    /**
     * The name of the Cosmos DB Mongo Database in which the Cosmos DB Mongo Collection is created. Changing this forces a new resource to be created.
     */
    public readonly databaseName!: kulado.Output<string>;
    /**
     * The default Time To Live in seconds. If the value is `-1` items are not automatically expired.
     */
    public readonly defaultTtlSeconds!: kulado.Output<number | undefined>;
    /**
     * One or more `indexes` blocks as defined below.
     */
    public readonly indexes!: kulado.Output<{ key: string, unique?: boolean }[] | undefined>;
    /**
     * Specifies the name of the Cosmos DB Mongo Collection. Changing this forces a new resource to be created.
     */
    public readonly name!: kulado.Output<string>;
    /**
     * The name of the resource group in which the Cosmos DB Mongo Collection is created. Changing this forces a new resource to be created.
     */
    public readonly resourceGroupName!: kulado.Output<string>;
    /**
     * The name of the key to partition on for sharding. There must not be any other unique index keys. 
     */
    public readonly shardKey!: kulado.Output<string | undefined>;

    /**
     * Create a MongoCollection resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: MongoCollectionArgs, opts?: kulado.CustomResourceOptions)
    constructor(name: string, argsOrState?: MongoCollectionArgs | MongoCollectionState, opts?: kulado.CustomResourceOptions) {
        let inputs: kulado.Inputs = {};
        if (opts && opts.id) {
            const state = argsOrState as MongoCollectionState | undefined;
            inputs["accountName"] = state ? state.accountName : undefined;
            inputs["databaseName"] = state ? state.databaseName : undefined;
            inputs["defaultTtlSeconds"] = state ? state.defaultTtlSeconds : undefined;
            inputs["indexes"] = state ? state.indexes : undefined;
            inputs["name"] = state ? state.name : undefined;
            inputs["resourceGroupName"] = state ? state.resourceGroupName : undefined;
            inputs["shardKey"] = state ? state.shardKey : undefined;
        } else {
            const args = argsOrState as MongoCollectionArgs | undefined;
            if (!args || args.accountName === undefined) {
                throw new Error("Missing required property 'accountName'");
            }
            if (!args || args.databaseName === undefined) {
                throw new Error("Missing required property 'databaseName'");
            }
            if (!args || args.resourceGroupName === undefined) {
                throw new Error("Missing required property 'resourceGroupName'");
            }
            inputs["accountName"] = args ? args.accountName : undefined;
            inputs["databaseName"] = args ? args.databaseName : undefined;
            inputs["defaultTtlSeconds"] = args ? args.defaultTtlSeconds : undefined;
            inputs["indexes"] = args ? args.indexes : undefined;
            inputs["name"] = args ? args.name : undefined;
            inputs["resourceGroupName"] = args ? args.resourceGroupName : undefined;
            inputs["shardKey"] = args ? args.shardKey : undefined;
        }
        super(MongoCollection.__kuladoType, name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering MongoCollection resources.
 */
export interface MongoCollectionState {
    readonly accountName?: kulado.Input<string>;
    /**
     * The name of the Cosmos DB Mongo Database in which the Cosmos DB Mongo Collection is created. Changing this forces a new resource to be created.
     */
    readonly databaseName?: kulado.Input<string>;
    /**
     * The default Time To Live in seconds. If the value is `-1` items are not automatically expired.
     */
    readonly defaultTtlSeconds?: kulado.Input<number>;
    /**
     * One or more `indexes` blocks as defined below.
     */
    readonly indexes?: kulado.Input<kulado.Input<{ key: kulado.Input<string>, unique?: kulado.Input<boolean> }>[]>;
    /**
     * Specifies the name of the Cosmos DB Mongo Collection. Changing this forces a new resource to be created.
     */
    readonly name?: kulado.Input<string>;
    /**
     * The name of the resource group in which the Cosmos DB Mongo Collection is created. Changing this forces a new resource to be created.
     */
    readonly resourceGroupName?: kulado.Input<string>;
    /**
     * The name of the key to partition on for sharding. There must not be any other unique index keys. 
     */
    readonly shardKey?: kulado.Input<string>;
}

/**
 * The set of arguments for constructing a MongoCollection resource.
 */
export interface MongoCollectionArgs {
    readonly accountName: kulado.Input<string>;
    /**
     * The name of the Cosmos DB Mongo Database in which the Cosmos DB Mongo Collection is created. Changing this forces a new resource to be created.
     */
    readonly databaseName: kulado.Input<string>;
    /**
     * The default Time To Live in seconds. If the value is `-1` items are not automatically expired.
     */
    readonly defaultTtlSeconds?: kulado.Input<number>;
    /**
     * One or more `indexes` blocks as defined below.
     */
    readonly indexes?: kulado.Input<kulado.Input<{ key: kulado.Input<string>, unique?: kulado.Input<boolean> }>[]>;
    /**
     * Specifies the name of the Cosmos DB Mongo Collection. Changing this forces a new resource to be created.
     */
    readonly name?: kulado.Input<string>;
    /**
     * The name of the resource group in which the Cosmos DB Mongo Collection is created. Changing this forces a new resource to be created.
     */
    readonly resourceGroupName: kulado.Input<string>;
    /**
     * The name of the key to partition on for sharding. There must not be any other unique index keys. 
     */
    readonly shardKey?: kulado.Input<string>;
}
