// *** WARNING: this file was generated by the Kulado Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as kulado from "@kulado/kulado";
import * as utilities from "../utilities";

/**
 * Enables you to manage Private DNS zones within Azure DNS. These zones are hosted on Azure's name servers.
 * 
 * ## Example Usage
 * 
 * ```typescript
 * import * as kulado from "@kulado/kulado";
 * import * as azure from "@kulado/azure";
 * 
 * const testResourceGroup = new azure.core.ResourceGroup("test", {
 *     location: "West US",
 *     name: "acceptanceTestResourceGroup1",
 * });
 * const testZone = new azure.privatedns.Zone("test", {
 *     name: "mydomain.com",
 *     resourceGroupName: testResourceGroup.name,
 * });
 * ```
 *
 * > This content is derived from https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/website/docs/r/private_dns_zone.html.markdown.
 */
export class Zone extends kulado.CustomResource {
    /**
     * Get an existing Zone resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     */
    public static get(name: string, id: kulado.Input<kulado.ID>, state?: ZoneState, opts?: kulado.CustomResourceOptions): Zone {
        return new Zone(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __kuladoType = 'azure:privatedns/zone:Zone';

    /**
     * Returns true if the given object is an instance of Zone.  This is designed to work even
     * when multiple copies of the Kulado SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Zone {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__kuladoType'] === Zone.__kuladoType;
    }

    /**
     * The maximum number of record sets that can be created in this Private DNS zone.
     */
    public /*out*/ readonly maxNumberOfRecordSets!: kulado.Output<number>;
    /**
     * The maximum number of virtual networks that can be linked to this Private DNS zone.
     */
    public /*out*/ readonly maxNumberOfVirtualNetworkLinks!: kulado.Output<number>;
    /**
     * The maximum number of virtual networks that can be linked to this Private DNS zone with registration enabled.
     */
    public /*out*/ readonly maxNumberOfVirtualNetworkLinksWithRegistration!: kulado.Output<number>;
    /**
     * The name of the Private DNS Zone. Must be a valid domain name.
     */
    public readonly name!: kulado.Output<string>;
    /**
     * The current number of record sets in this Private DNS zone.
     */
    public /*out*/ readonly numberOfRecordSets!: kulado.Output<number>;
    /**
     * Specifies the resource group where the resource exists. Changing this forces a new resource to be created.
     */
    public readonly resourceGroupName!: kulado.Output<string>;
    /**
     * A mapping of tags to assign to the resource.
     */
    public readonly tags!: kulado.Output<{[key: string]: any}>;

    /**
     * Create a Zone resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ZoneArgs, opts?: kulado.CustomResourceOptions)
    constructor(name: string, argsOrState?: ZoneArgs | ZoneState, opts?: kulado.CustomResourceOptions) {
        let inputs: kulado.Inputs = {};
        if (opts && opts.id) {
            const state = argsOrState as ZoneState | undefined;
            inputs["maxNumberOfRecordSets"] = state ? state.maxNumberOfRecordSets : undefined;
            inputs["maxNumberOfVirtualNetworkLinks"] = state ? state.maxNumberOfVirtualNetworkLinks : undefined;
            inputs["maxNumberOfVirtualNetworkLinksWithRegistration"] = state ? state.maxNumberOfVirtualNetworkLinksWithRegistration : undefined;
            inputs["name"] = state ? state.name : undefined;
            inputs["numberOfRecordSets"] = state ? state.numberOfRecordSets : undefined;
            inputs["resourceGroupName"] = state ? state.resourceGroupName : undefined;
            inputs["tags"] = state ? state.tags : undefined;
        } else {
            const args = argsOrState as ZoneArgs | undefined;
            if (!args || args.resourceGroupName === undefined) {
                throw new Error("Missing required property 'resourceGroupName'");
            }
            inputs["name"] = args ? args.name : undefined;
            inputs["resourceGroupName"] = args ? args.resourceGroupName : undefined;
            inputs["tags"] = args ? args.tags : undefined;
            inputs["maxNumberOfRecordSets"] = undefined /*out*/;
            inputs["maxNumberOfVirtualNetworkLinks"] = undefined /*out*/;
            inputs["maxNumberOfVirtualNetworkLinksWithRegistration"] = undefined /*out*/;
            inputs["numberOfRecordSets"] = undefined /*out*/;
        }
        super(Zone.__kuladoType, name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Zone resources.
 */
export interface ZoneState {
    /**
     * The maximum number of record sets that can be created in this Private DNS zone.
     */
    readonly maxNumberOfRecordSets?: kulado.Input<number>;
    /**
     * The maximum number of virtual networks that can be linked to this Private DNS zone.
     */
    readonly maxNumberOfVirtualNetworkLinks?: kulado.Input<number>;
    /**
     * The maximum number of virtual networks that can be linked to this Private DNS zone with registration enabled.
     */
    readonly maxNumberOfVirtualNetworkLinksWithRegistration?: kulado.Input<number>;
    /**
     * The name of the Private DNS Zone. Must be a valid domain name.
     */
    readonly name?: kulado.Input<string>;
    /**
     * The current number of record sets in this Private DNS zone.
     */
    readonly numberOfRecordSets?: kulado.Input<number>;
    /**
     * Specifies the resource group where the resource exists. Changing this forces a new resource to be created.
     */
    readonly resourceGroupName?: kulado.Input<string>;
    /**
     * A mapping of tags to assign to the resource.
     */
    readonly tags?: kulado.Input<{[key: string]: any}>;
}

/**
 * The set of arguments for constructing a Zone resource.
 */
export interface ZoneArgs {
    /**
     * The name of the Private DNS Zone. Must be a valid domain name.
     */
    readonly name?: kulado.Input<string>;
    /**
     * Specifies the resource group where the resource exists. Changing this forces a new resource to be created.
     */
    readonly resourceGroupName: kulado.Input<string>;
    /**
     * A mapping of tags to assign to the resource.
     */
    readonly tags?: kulado.Input<{[key: string]: any}>;
}
