// *** WARNING: this file was generated by the Kulado Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as kulado from "@kulado/kulado";
import * as utilities from "../utilities";

/**
 * Manage a Azure Data Lake Store Firewall Rule.
 * 
 * ## Example Usage
 * 
 * ```typescript
 * import * as kulado from "@kulado/kulado";
 * import * as azure from "@kulado/azure";
 * 
 * const exampleResourceGroup = new azure.core.ResourceGroup("example", {
 *     location: "northeurope",
 *     name: "example",
 * });
 * const exampleStore = new azure.datalake.Store("example", {
 *     location: exampleResourceGroup.location,
 *     name: "consumptiondatalake",
 *     resourceGroupName: exampleResourceGroup.name,
 * });
 * const exampleStoreFirewallRule = new azure.datalake.StoreFirewallRule("example", {
 *     accountName: exampleStore.name,
 *     endIpAddress: "2.3.4.5",
 *     name: "office-ip-range",
 *     resourceGroupName: exampleResourceGroup.name,
 *     startIpAddress: "1.2.3.4",
 * });
 * ```
 *
 * > This content is derived from https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/website/docs/r/data_lake_store_firewall_rule.html.markdown.
 */
export class StoreFirewallRule extends kulado.CustomResource {
    /**
     * Get an existing StoreFirewallRule resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     */
    public static get(name: string, id: kulado.Input<kulado.ID>, state?: StoreFirewallRuleState, opts?: kulado.CustomResourceOptions): StoreFirewallRule {
        return new StoreFirewallRule(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __kuladoType = 'azure:datalake/storeFirewallRule:StoreFirewallRule';

    /**
     * Returns true if the given object is an instance of StoreFirewallRule.  This is designed to work even
     * when multiple copies of the Kulado SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is StoreFirewallRule {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__kuladoType'] === StoreFirewallRule.__kuladoType;
    }

    /**
     * Specifies the name of the Data Lake Store for which the Firewall Rule should take effect.
     */
    public readonly accountName!: kulado.Output<string>;
    /**
     * The End IP Address for the firewall rule.
     */
    public readonly endIpAddress!: kulado.Output<string>;
    /**
     * Specifies the name of the Data Lake Store. Changing this forces a new resource to be created. Has to be between 3 to 24 characters.
     */
    public readonly name!: kulado.Output<string>;
    /**
     * The name of the resource group in which to create the Data Lake Store.
     */
    public readonly resourceGroupName!: kulado.Output<string>;
    /**
     * The Start IP address for the firewall rule.
     */
    public readonly startIpAddress!: kulado.Output<string>;

    /**
     * Create a StoreFirewallRule resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: StoreFirewallRuleArgs, opts?: kulado.CustomResourceOptions)
    constructor(name: string, argsOrState?: StoreFirewallRuleArgs | StoreFirewallRuleState, opts?: kulado.CustomResourceOptions) {
        let inputs: kulado.Inputs = {};
        if (opts && opts.id) {
            const state = argsOrState as StoreFirewallRuleState | undefined;
            inputs["accountName"] = state ? state.accountName : undefined;
            inputs["endIpAddress"] = state ? state.endIpAddress : undefined;
            inputs["name"] = state ? state.name : undefined;
            inputs["resourceGroupName"] = state ? state.resourceGroupName : undefined;
            inputs["startIpAddress"] = state ? state.startIpAddress : undefined;
        } else {
            const args = argsOrState as StoreFirewallRuleArgs | undefined;
            if (!args || args.accountName === undefined) {
                throw new Error("Missing required property 'accountName'");
            }
            if (!args || args.endIpAddress === undefined) {
                throw new Error("Missing required property 'endIpAddress'");
            }
            if (!args || args.resourceGroupName === undefined) {
                throw new Error("Missing required property 'resourceGroupName'");
            }
            if (!args || args.startIpAddress === undefined) {
                throw new Error("Missing required property 'startIpAddress'");
            }
            inputs["accountName"] = args ? args.accountName : undefined;
            inputs["endIpAddress"] = args ? args.endIpAddress : undefined;
            inputs["name"] = args ? args.name : undefined;
            inputs["resourceGroupName"] = args ? args.resourceGroupName : undefined;
            inputs["startIpAddress"] = args ? args.startIpAddress : undefined;
        }
        super(StoreFirewallRule.__kuladoType, name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering StoreFirewallRule resources.
 */
export interface StoreFirewallRuleState {
    /**
     * Specifies the name of the Data Lake Store for which the Firewall Rule should take effect.
     */
    readonly accountName?: kulado.Input<string>;
    /**
     * The End IP Address for the firewall rule.
     */
    readonly endIpAddress?: kulado.Input<string>;
    /**
     * Specifies the name of the Data Lake Store. Changing this forces a new resource to be created. Has to be between 3 to 24 characters.
     */
    readonly name?: kulado.Input<string>;
    /**
     * The name of the resource group in which to create the Data Lake Store.
     */
    readonly resourceGroupName?: kulado.Input<string>;
    /**
     * The Start IP address for the firewall rule.
     */
    readonly startIpAddress?: kulado.Input<string>;
}

/**
 * The set of arguments for constructing a StoreFirewallRule resource.
 */
export interface StoreFirewallRuleArgs {
    /**
     * Specifies the name of the Data Lake Store for which the Firewall Rule should take effect.
     */
    readonly accountName: kulado.Input<string>;
    /**
     * The End IP Address for the firewall rule.
     */
    readonly endIpAddress: kulado.Input<string>;
    /**
     * Specifies the name of the Data Lake Store. Changing this forces a new resource to be created. Has to be between 3 to 24 characters.
     */
    readonly name?: kulado.Input<string>;
    /**
     * The name of the resource group in which to create the Data Lake Store.
     */
    readonly resourceGroupName: kulado.Input<string>;
    /**
     * The Start IP address for the firewall rule.
     */
    readonly startIpAddress: kulado.Input<string>;
}
