// *** WARNING: this file was generated by the Kulado Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package dns

import (
	"github.com/pkg/errors"
	"github.com/kulado/kulado/sdk/go/kulado"
)

// Enables you to manage DNS CNAME Records within Azure DNS.
//
// > This content is derived from https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/website/docs/r/dns_cname_record.html.markdown.
type CNameRecord struct {
	s *kulado.ResourceState
}

// NewCNameRecord registers a new resource with the given unique name, arguments, and options.
func NewCNameRecord(ctx *kulado.Context,
	name string, args *CNameRecordArgs, opts ...kulado.ResourceOpt) (*CNameRecord, error) {
	if args == nil || args.Record == nil {
		return nil, errors.New("missing required argument 'Record'")
	}
	if args == nil || args.ResourceGroupName == nil {
		return nil, errors.New("missing required argument 'ResourceGroupName'")
	}
	if args == nil || args.Ttl == nil {
		return nil, errors.New("missing required argument 'Ttl'")
	}
	if args == nil || args.ZoneName == nil {
		return nil, errors.New("missing required argument 'ZoneName'")
	}
	inputs := make(map[string]interface{})
	if args == nil {
		inputs["name"] = nil
		inputs["record"] = nil
		inputs["resourceGroupName"] = nil
		inputs["tags"] = nil
		inputs["ttl"] = nil
		inputs["zoneName"] = nil
	} else {
		inputs["name"] = args.Name
		inputs["record"] = args.Record
		inputs["resourceGroupName"] = args.ResourceGroupName
		inputs["tags"] = args.Tags
		inputs["ttl"] = args.Ttl
		inputs["zoneName"] = args.ZoneName
	}
	s, err := ctx.RegisterResource("azure:dns/cNameRecord:CNameRecord", name, true, inputs, opts...)
	if err != nil {
		return nil, err
	}
	return &CNameRecord{s: s}, nil
}

// GetCNameRecord gets an existing CNameRecord resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetCNameRecord(ctx *kulado.Context,
	name string, id kulado.ID, state *CNameRecordState, opts ...kulado.ResourceOpt) (*CNameRecord, error) {
	inputs := make(map[string]interface{})
	if state != nil {
		inputs["name"] = state.Name
		inputs["record"] = state.Record
		inputs["resourceGroupName"] = state.ResourceGroupName
		inputs["tags"] = state.Tags
		inputs["ttl"] = state.Ttl
		inputs["zoneName"] = state.ZoneName
	}
	s, err := ctx.ReadResource("azure:dns/cNameRecord:CNameRecord", name, id, inputs, opts...)
	if err != nil {
		return nil, err
	}
	return &CNameRecord{s: s}, nil
}

// URN is this resource's unique name assigned by Kulado.
func (r *CNameRecord) URN() *kulado.URNOutput {
	return r.s.URN()
}

// ID is this resource's unique identifier assigned by its provider.
func (r *CNameRecord) ID() *kulado.IDOutput {
	return r.s.ID()
}

// The name of the DNS CNAME Record.
func (r *CNameRecord) Name() *kulado.StringOutput {
	return (*kulado.StringOutput)(r.s.State["name"])
}

// The target of the CNAME.
func (r *CNameRecord) Record() *kulado.StringOutput {
	return (*kulado.StringOutput)(r.s.State["record"])
}

// Specifies the resource group where the resource exists. Changing this forces a new resource to be created.
func (r *CNameRecord) ResourceGroupName() *kulado.StringOutput {
	return (*kulado.StringOutput)(r.s.State["resourceGroupName"])
}

// A mapping of tags to assign to the resource.
func (r *CNameRecord) Tags() *kulado.MapOutput {
	return (*kulado.MapOutput)(r.s.State["tags"])
}

func (r *CNameRecord) Ttl() *kulado.IntOutput {
	return (*kulado.IntOutput)(r.s.State["ttl"])
}

// Specifies the DNS Zone where the resource exists. Changing this forces a new resource to be created.
func (r *CNameRecord) ZoneName() *kulado.StringOutput {
	return (*kulado.StringOutput)(r.s.State["zoneName"])
}

// Input properties used for looking up and filtering CNameRecord resources.
type CNameRecordState struct {
	// The name of the DNS CNAME Record.
	Name interface{}
	// The target of the CNAME.
	Record interface{}
	// Specifies the resource group where the resource exists. Changing this forces a new resource to be created.
	ResourceGroupName interface{}
	// A mapping of tags to assign to the resource.
	Tags interface{}
	Ttl interface{}
	// Specifies the DNS Zone where the resource exists. Changing this forces a new resource to be created.
	ZoneName interface{}
}

// The set of arguments for constructing a CNameRecord resource.
type CNameRecordArgs struct {
	// The name of the DNS CNAME Record.
	Name interface{}
	// The target of the CNAME.
	Record interface{}
	// Specifies the resource group where the resource exists. Changing this forces a new resource to be created.
	ResourceGroupName interface{}
	// A mapping of tags to assign to the resource.
	Tags interface{}
	Ttl interface{}
	// Specifies the DNS Zone where the resource exists. Changing this forces a new resource to be created.
	ZoneName interface{}
}
