// *** WARNING: this file was generated by the Kulado Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as kulado from "@kulado/kulado";
import * as utilities from "../utilities";

/**
 * Manages a Dev Test Lab.
 * 
 * ## Example Usage
 * 
 * ```typescript
 * import * as kulado from "@kulado/kulado";
 * import * as azure from "@kulado/azure";
 * 
 * const testResourceGroup = new azure.core.ResourceGroup("test", {
 *     location: "West US",
 *     name: "example-resources",
 * });
 * const testLab = new azure.devtest.Lab("test", {
 *     location: testResourceGroup.location,
 *     name: "example-devtestlab",
 *     resourceGroupName: testResourceGroup.name,
 *     tags: {
 *         Sydney: "Australia",
 *     },
 * });
 * ```
 *
 * > This content is derived from https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/website/docs/r/dev_test_lab.html.markdown.
 */
export class Lab extends kulado.CustomResource {
    /**
     * Get an existing Lab resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     */
    public static get(name: string, id: kulado.Input<kulado.ID>, state?: LabState, opts?: kulado.CustomResourceOptions): Lab {
        return new Lab(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __kuladoType = 'azure:devtest/lab:Lab';

    /**
     * Returns true if the given object is an instance of Lab.  This is designed to work even
     * when multiple copies of the Kulado SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Lab {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__kuladoType'] === Lab.__kuladoType;
    }

    /**
     * The ID of the Storage Account used for Artifact Storage.
     */
    public /*out*/ readonly artifactsStorageAccountId!: kulado.Output<string>;
    /**
     * The ID of the Default Premium Storage Account for this Dev Test Lab.
     */
    public /*out*/ readonly defaultPremiumStorageAccountId!: kulado.Output<string>;
    /**
     * The ID of the Default Storage Account for this Dev Test Lab.
     */
    public /*out*/ readonly defaultStorageAccountId!: kulado.Output<string>;
    /**
     * The ID of the Key used for this Dev Test Lab.
     */
    public /*out*/ readonly keyVaultId!: kulado.Output<string>;
    /**
     * Specifies the supported Azure location where the Dev Test Lab should exist. Changing this forces a new resource to be created.
     */
    public readonly location!: kulado.Output<string>;
    /**
     * Specifies the name of the Dev Test Lab. Changing this forces a new resource to be created.
     */
    public readonly name!: kulado.Output<string>;
    /**
     * The ID of the Storage Account used for Storage of Premium Data Disk.
     */
    public /*out*/ readonly premiumDataDiskStorageAccountId!: kulado.Output<string>;
    /**
     * The name of the resource group under which the Dev Test Lab resource has to be created. Changing this forces a new resource to be created.
     */
    public readonly resourceGroupName!: kulado.Output<string>;
    /**
     * The type of storage used by the Dev Test Lab. Possible values are `Standard` and `Premium`. Defaults to `Premium`. Changing this forces a new resource to be created.
     */
    public readonly storageType!: kulado.Output<string | undefined>;
    /**
     * A mapping of tags to assign to the resource.
     */
    public readonly tags!: kulado.Output<{[key: string]: any}>;
    /**
     * The unique immutable identifier of the Dev Test Lab.
     */
    public /*out*/ readonly uniqueIdentifier!: kulado.Output<string>;

    /**
     * Create a Lab resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: LabArgs, opts?: kulado.CustomResourceOptions)
    constructor(name: string, argsOrState?: LabArgs | LabState, opts?: kulado.CustomResourceOptions) {
        let inputs: kulado.Inputs = {};
        if (opts && opts.id) {
            const state = argsOrState as LabState | undefined;
            inputs["artifactsStorageAccountId"] = state ? state.artifactsStorageAccountId : undefined;
            inputs["defaultPremiumStorageAccountId"] = state ? state.defaultPremiumStorageAccountId : undefined;
            inputs["defaultStorageAccountId"] = state ? state.defaultStorageAccountId : undefined;
            inputs["keyVaultId"] = state ? state.keyVaultId : undefined;
            inputs["location"] = state ? state.location : undefined;
            inputs["name"] = state ? state.name : undefined;
            inputs["premiumDataDiskStorageAccountId"] = state ? state.premiumDataDiskStorageAccountId : undefined;
            inputs["resourceGroupName"] = state ? state.resourceGroupName : undefined;
            inputs["storageType"] = state ? state.storageType : undefined;
            inputs["tags"] = state ? state.tags : undefined;
            inputs["uniqueIdentifier"] = state ? state.uniqueIdentifier : undefined;
        } else {
            const args = argsOrState as LabArgs | undefined;
            if (!args || args.resourceGroupName === undefined) {
                throw new Error("Missing required property 'resourceGroupName'");
            }
            inputs["location"] = args ? args.location : undefined;
            inputs["name"] = args ? args.name : undefined;
            inputs["resourceGroupName"] = args ? args.resourceGroupName : undefined;
            inputs["storageType"] = args ? args.storageType : undefined;
            inputs["tags"] = args ? args.tags : undefined;
            inputs["artifactsStorageAccountId"] = undefined /*out*/;
            inputs["defaultPremiumStorageAccountId"] = undefined /*out*/;
            inputs["defaultStorageAccountId"] = undefined /*out*/;
            inputs["keyVaultId"] = undefined /*out*/;
            inputs["premiumDataDiskStorageAccountId"] = undefined /*out*/;
            inputs["uniqueIdentifier"] = undefined /*out*/;
        }
        super(Lab.__kuladoType, name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Lab resources.
 */
export interface LabState {
    /**
     * The ID of the Storage Account used for Artifact Storage.
     */
    readonly artifactsStorageAccountId?: kulado.Input<string>;
    /**
     * The ID of the Default Premium Storage Account for this Dev Test Lab.
     */
    readonly defaultPremiumStorageAccountId?: kulado.Input<string>;
    /**
     * The ID of the Default Storage Account for this Dev Test Lab.
     */
    readonly defaultStorageAccountId?: kulado.Input<string>;
    /**
     * The ID of the Key used for this Dev Test Lab.
     */
    readonly keyVaultId?: kulado.Input<string>;
    /**
     * Specifies the supported Azure location where the Dev Test Lab should exist. Changing this forces a new resource to be created.
     */
    readonly location?: kulado.Input<string>;
    /**
     * Specifies the name of the Dev Test Lab. Changing this forces a new resource to be created.
     */
    readonly name?: kulado.Input<string>;
    /**
     * The ID of the Storage Account used for Storage of Premium Data Disk.
     */
    readonly premiumDataDiskStorageAccountId?: kulado.Input<string>;
    /**
     * The name of the resource group under which the Dev Test Lab resource has to be created. Changing this forces a new resource to be created.
     */
    readonly resourceGroupName?: kulado.Input<string>;
    /**
     * The type of storage used by the Dev Test Lab. Possible values are `Standard` and `Premium`. Defaults to `Premium`. Changing this forces a new resource to be created.
     */
    readonly storageType?: kulado.Input<string>;
    /**
     * A mapping of tags to assign to the resource.
     */
    readonly tags?: kulado.Input<{[key: string]: any}>;
    /**
     * The unique immutable identifier of the Dev Test Lab.
     */
    readonly uniqueIdentifier?: kulado.Input<string>;
}

/**
 * The set of arguments for constructing a Lab resource.
 */
export interface LabArgs {
    /**
     * Specifies the supported Azure location where the Dev Test Lab should exist. Changing this forces a new resource to be created.
     */
    readonly location?: kulado.Input<string>;
    /**
     * Specifies the name of the Dev Test Lab. Changing this forces a new resource to be created.
     */
    readonly name?: kulado.Input<string>;
    /**
     * The name of the resource group under which the Dev Test Lab resource has to be created. Changing this forces a new resource to be created.
     */
    readonly resourceGroupName: kulado.Input<string>;
    /**
     * The type of storage used by the Dev Test Lab. Possible values are `Standard` and `Premium`. Defaults to `Premium`. Changing this forces a new resource to be created.
     */
    readonly storageType?: kulado.Input<string>;
    /**
     * A mapping of tags to assign to the resource.
     */
    readonly tags?: kulado.Input<{[key: string]: any}>;
}
