// *** WARNING: this file was generated by the Kulado Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as kulado from "@kulado/kulado";
import * as utilities from "../utilities";

/**
 * Use this data source to access information about an existing Notification Hub within a Notification Hub Namespace.
 * 
 * ## Example Usage
 * 
 * ```typescript
 * import * as kulado from "@kulado/kulado";
 * import * as azure from "@kulado/azure";
 * 
 * const test = kulado.output(azure.notificationhub.getHub({
 *     name: "notification-hub",
 *     namespaceName: "namespace-name",
 *     resourceGroupName: "resource-group-name",
 * }));
 * 
 * export const id = test.id;
 * ```
 *
 * > This content is derived from https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/website/docs/d/notification_hub.html.markdown.
 */
export function getHub(args: GetHubArgs, opts?: kulado.InvokeOptions): Promise<GetHubResult> & GetHubResult {
    const promise: Promise<GetHubResult> = kulado.runtime.invoke("azure:notificationhub/getHub:getHub", {
        "name": args.name,
        "namespaceName": args.namespaceName,
        "resourceGroupName": args.resourceGroupName,
    }, opts);

    return kulado.utils.liftProperties(promise, opts);
}

/**
 * A collection of arguments for invoking getHub.
 */
export interface GetHubArgs {
    /**
     * Specifies the Name of the Notification Hub.
     */
    readonly name: string;
    /**
     * Specifies the Name of the Notification Hub Namespace which contains the Notification Hub.
     */
    readonly namespaceName: string;
    /**
     * Specifies the Name of the Resource Group within which the Notification Hub exists.
     */
    readonly resourceGroupName: string;
}

/**
 * A collection of values returned by getHub.
 */
export interface GetHubResult {
    /**
     * A `apns_credential` block as defined below.
     */
    readonly apnsCredentials: { applicationMode: string, bundleId: string, keyId: string, teamId: string, token: string }[];
    /**
     * A `gcm_credential` block as defined below.
     */
    readonly gcmCredentials: { apiKey: string }[];
    /**
     * The Azure Region in which this Notification Hub exists.
     */
    readonly location: string;
    readonly name: string;
    readonly namespaceName: string;
    readonly resourceGroupName: string;
    /**
     * id is the provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
}
