// *** WARNING: this file was generated by the Kulado Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as kulado from "@kulado/kulado";
import * as utilities from "../utilities";

/**
 * Manages a Notification Hub Namespace.
 * 
 * ## Example Usage
 * 
 * ```typescript
 * import * as kulado from "@kulado/kulado";
 * import * as azure from "@kulado/azure";
 * 
 * const testResourceGroup = new azure.core.ResourceGroup("test", {
 *     location: "Australia East",
 *     name: "notificationhub-resources",
 * });
 * const testNamespace = new azure.notificationhub.Namespace("test", {
 *     location: testResourceGroup.location,
 *     name: "myappnamespace",
 *     namespaceType: "NotificationHub",
 *     resourceGroupName: testResourceGroup.name,
 *     skuName: "Free",
 * });
 * ```
 *
 * > This content is derived from https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/website/docs/r/notification_hub_namespace.html.markdown.
 */
export class Namespace extends kulado.CustomResource {
    /**
     * Get an existing Namespace resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     */
    public static get(name: string, id: kulado.Input<kulado.ID>, state?: NamespaceState, opts?: kulado.CustomResourceOptions): Namespace {
        return new Namespace(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __kuladoType = 'azure:notificationhub/namespace:Namespace';

    /**
     * Returns true if the given object is an instance of Namespace.  This is designed to work even
     * when multiple copies of the Kulado SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Namespace {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__kuladoType'] === Namespace.__kuladoType;
    }

    /**
     * Is this Notification Hub Namespace enabled? Defaults to `true`.
     */
    public readonly enabled!: kulado.Output<boolean | undefined>;
    /**
     * The Azure Region in which this Notification Hub Namespace should be created.
     */
    public readonly location!: kulado.Output<string>;
    /**
     * The name to use for this Notification Hub Namespace. Changing this forces a new resource to be created.
     */
    public readonly name!: kulado.Output<string>;
    /**
     * The Type of Namespace - possible values are `Messaging` or `NotificationHub`. Changing this forces a new resource to be created.
     */
    public readonly namespaceType!: kulado.Output<string>;
    /**
     * The name of the Resource Group in which the Notification Hub Namespace should exist. Changing this forces a new resource to be created.
     */
    public readonly resourceGroupName!: kulado.Output<string>;
    /**
     * The ServiceBus Endpoint for this Notification Hub Namespace.
     */
    public /*out*/ readonly servicebusEndpoint!: kulado.Output<string>;
    /**
     * ) A `sku` block as described below.
     */
    public readonly sku!: kulado.Output<{ name: string }>;
    /**
     * The name of the SKU to use for this Notification Hub Namespace. Possible values are `Free`, `Basic` or `Standard`. Changing this forces a new resource to be created.
     */
    public readonly skuName!: kulado.Output<string>;

    /**
     * Create a Namespace resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: NamespaceArgs, opts?: kulado.CustomResourceOptions)
    constructor(name: string, argsOrState?: NamespaceArgs | NamespaceState, opts?: kulado.CustomResourceOptions) {
        let inputs: kulado.Inputs = {};
        if (opts && opts.id) {
            const state = argsOrState as NamespaceState | undefined;
            inputs["enabled"] = state ? state.enabled : undefined;
            inputs["location"] = state ? state.location : undefined;
            inputs["name"] = state ? state.name : undefined;
            inputs["namespaceType"] = state ? state.namespaceType : undefined;
            inputs["resourceGroupName"] = state ? state.resourceGroupName : undefined;
            inputs["servicebusEndpoint"] = state ? state.servicebusEndpoint : undefined;
            inputs["sku"] = state ? state.sku : undefined;
            inputs["skuName"] = state ? state.skuName : undefined;
        } else {
            const args = argsOrState as NamespaceArgs | undefined;
            if (!args || args.namespaceType === undefined) {
                throw new Error("Missing required property 'namespaceType'");
            }
            if (!args || args.resourceGroupName === undefined) {
                throw new Error("Missing required property 'resourceGroupName'");
            }
            inputs["enabled"] = args ? args.enabled : undefined;
            inputs["location"] = args ? args.location : undefined;
            inputs["name"] = args ? args.name : undefined;
            inputs["namespaceType"] = args ? args.namespaceType : undefined;
            inputs["resourceGroupName"] = args ? args.resourceGroupName : undefined;
            inputs["sku"] = args ? args.sku : undefined;
            inputs["skuName"] = args ? args.skuName : undefined;
            inputs["servicebusEndpoint"] = undefined /*out*/;
        }
        super(Namespace.__kuladoType, name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Namespace resources.
 */
export interface NamespaceState {
    /**
     * Is this Notification Hub Namespace enabled? Defaults to `true`.
     */
    readonly enabled?: kulado.Input<boolean>;
    /**
     * The Azure Region in which this Notification Hub Namespace should be created.
     */
    readonly location?: kulado.Input<string>;
    /**
     * The name to use for this Notification Hub Namespace. Changing this forces a new resource to be created.
     */
    readonly name?: kulado.Input<string>;
    /**
     * The Type of Namespace - possible values are `Messaging` or `NotificationHub`. Changing this forces a new resource to be created.
     */
    readonly namespaceType?: kulado.Input<string>;
    /**
     * The name of the Resource Group in which the Notification Hub Namespace should exist. Changing this forces a new resource to be created.
     */
    readonly resourceGroupName?: kulado.Input<string>;
    /**
     * The ServiceBus Endpoint for this Notification Hub Namespace.
     */
    readonly servicebusEndpoint?: kulado.Input<string>;
    /**
     * ) A `sku` block as described below.
     */
    readonly sku?: kulado.Input<{ name: kulado.Input<string> }>;
    /**
     * The name of the SKU to use for this Notification Hub Namespace. Possible values are `Free`, `Basic` or `Standard`. Changing this forces a new resource to be created.
     */
    readonly skuName?: kulado.Input<string>;
}

/**
 * The set of arguments for constructing a Namespace resource.
 */
export interface NamespaceArgs {
    /**
     * Is this Notification Hub Namespace enabled? Defaults to `true`.
     */
    readonly enabled?: kulado.Input<boolean>;
    /**
     * The Azure Region in which this Notification Hub Namespace should be created.
     */
    readonly location?: kulado.Input<string>;
    /**
     * The name to use for this Notification Hub Namespace. Changing this forces a new resource to be created.
     */
    readonly name?: kulado.Input<string>;
    /**
     * The Type of Namespace - possible values are `Messaging` or `NotificationHub`. Changing this forces a new resource to be created.
     */
    readonly namespaceType: kulado.Input<string>;
    /**
     * The name of the Resource Group in which the Notification Hub Namespace should exist. Changing this forces a new resource to be created.
     */
    readonly resourceGroupName: kulado.Input<string>;
    /**
     * ) A `sku` block as described below.
     */
    readonly sku?: kulado.Input<{ name: kulado.Input<string> }>;
    /**
     * The name of the SKU to use for this Notification Hub Namespace. Possible values are `Free`, `Basic` or `Standard`. Changing this forces a new resource to be created.
     */
    readonly skuName?: kulado.Input<string>;
}
