// *** WARNING: this file was generated by the Kulado Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package automation

import (
	"github.com/pkg/errors"
	"github.com/kulado/kulado/sdk/go/kulado"
)

// Manages a boolean variable in Azure Automation
//
// > This content is derived from https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/website/docs/r/automation_variable_bool.html.markdown.
type BoolVariable struct {
	s *kulado.ResourceState
}

// NewBoolVariable registers a new resource with the given unique name, arguments, and options.
func NewBoolVariable(ctx *kulado.Context,
	name string, args *BoolVariableArgs, opts ...kulado.ResourceOpt) (*BoolVariable, error) {
	if args == nil || args.AutomationAccountName == nil {
		return nil, errors.New("missing required argument 'AutomationAccountName'")
	}
	if args == nil || args.ResourceGroupName == nil {
		return nil, errors.New("missing required argument 'ResourceGroupName'")
	}
	inputs := make(map[string]interface{})
	if args == nil {
		inputs["automationAccountName"] = nil
		inputs["description"] = nil
		inputs["encrypted"] = nil
		inputs["name"] = nil
		inputs["resourceGroupName"] = nil
		inputs["value"] = nil
	} else {
		inputs["automationAccountName"] = args.AutomationAccountName
		inputs["description"] = args.Description
		inputs["encrypted"] = args.Encrypted
		inputs["name"] = args.Name
		inputs["resourceGroupName"] = args.ResourceGroupName
		inputs["value"] = args.Value
	}
	s, err := ctx.RegisterResource("azure:automation/boolVariable:BoolVariable", name, true, inputs, opts...)
	if err != nil {
		return nil, err
	}
	return &BoolVariable{s: s}, nil
}

// GetBoolVariable gets an existing BoolVariable resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetBoolVariable(ctx *kulado.Context,
	name string, id kulado.ID, state *BoolVariableState, opts ...kulado.ResourceOpt) (*BoolVariable, error) {
	inputs := make(map[string]interface{})
	if state != nil {
		inputs["automationAccountName"] = state.AutomationAccountName
		inputs["description"] = state.Description
		inputs["encrypted"] = state.Encrypted
		inputs["name"] = state.Name
		inputs["resourceGroupName"] = state.ResourceGroupName
		inputs["value"] = state.Value
	}
	s, err := ctx.ReadResource("azure:automation/boolVariable:BoolVariable", name, id, inputs, opts...)
	if err != nil {
		return nil, err
	}
	return &BoolVariable{s: s}, nil
}

// URN is this resource's unique name assigned by Kulado.
func (r *BoolVariable) URN() *kulado.URNOutput {
	return r.s.URN()
}

// ID is this resource's unique identifier assigned by its provider.
func (r *BoolVariable) ID() *kulado.IDOutput {
	return r.s.ID()
}

// The name of the automation account in which the Variable is created. Changing this forces a new resource to be created.
func (r *BoolVariable) AutomationAccountName() *kulado.StringOutput {
	return (*kulado.StringOutput)(r.s.State["automationAccountName"])
}

// The description of the Automation Variable.
func (r *BoolVariable) Description() *kulado.StringOutput {
	return (*kulado.StringOutput)(r.s.State["description"])
}

// Specifies if the Automation Variable is encrypted. Defaults to `false`.
func (r *BoolVariable) Encrypted() *kulado.BoolOutput {
	return (*kulado.BoolOutput)(r.s.State["encrypted"])
}

// The name of the Automation Variable. Changing this forces a new resource to be created.
func (r *BoolVariable) Name() *kulado.StringOutput {
	return (*kulado.StringOutput)(r.s.State["name"])
}

// The name of the resource group in which to create the Automation Variable. Changing this forces a new resource to be created.
func (r *BoolVariable) ResourceGroupName() *kulado.StringOutput {
	return (*kulado.StringOutput)(r.s.State["resourceGroupName"])
}

// The value of the Automation Variable as a `boolean`.
func (r *BoolVariable) Value() *kulado.BoolOutput {
	return (*kulado.BoolOutput)(r.s.State["value"])
}

// Input properties used for looking up and filtering BoolVariable resources.
type BoolVariableState struct {
	// The name of the automation account in which the Variable is created. Changing this forces a new resource to be created.
	AutomationAccountName interface{}
	// The description of the Automation Variable.
	Description interface{}
	// Specifies if the Automation Variable is encrypted. Defaults to `false`.
	Encrypted interface{}
	// The name of the Automation Variable. Changing this forces a new resource to be created.
	Name interface{}
	// The name of the resource group in which to create the Automation Variable. Changing this forces a new resource to be created.
	ResourceGroupName interface{}
	// The value of the Automation Variable as a `boolean`.
	Value interface{}
}

// The set of arguments for constructing a BoolVariable resource.
type BoolVariableArgs struct {
	// The name of the automation account in which the Variable is created. Changing this forces a new resource to be created.
	AutomationAccountName interface{}
	// The description of the Automation Variable.
	Description interface{}
	// Specifies if the Automation Variable is encrypted. Defaults to `false`.
	Encrypted interface{}
	// The name of the Automation Variable. Changing this forces a new resource to be created.
	Name interface{}
	// The name of the resource group in which to create the Automation Variable. Changing this forces a new resource to be created.
	ResourceGroupName interface{}
	// The value of the Automation Variable as a `boolean`.
	Value interface{}
}
