// *** WARNING: this file was generated by the Kulado Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as kulado from "@kulado/kulado";
import * as utilities from "../utilities";

/**
 * Use this data source to access information about an existing Load Balancer Backend Address Pool.
 * 
 * ## Example Usage
 * 
 * ```typescript
 * import * as kulado from "@kulado/kulado";
 * import * as azure from "@kulado/azure";
 * 
 * const testLB = kulado.output(azure.lb.getLB({
 *     name: "example-lb",
 *     resourceGroupName: "example-resources",
 * }));
 * const testBackendAddressPool = testLB.apply(testLB => azure.lb.getBackendAddressPool({
 *     loadbalancerId: testLB.id,
 *     name: "first",
 * }));
 * 
 * export const backendAddressPoolId = testBackendAddressPool.id;
 * ```
 *
 * > This content is derived from https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/website/docs/d/lb_backend_address_pool.html.markdown.
 */
export function getBackendAddressPool(args: GetBackendAddressPoolArgs, opts?: kulado.InvokeOptions): Promise<GetBackendAddressPoolResult> & GetBackendAddressPoolResult {
    const promise: Promise<GetBackendAddressPoolResult> = kulado.runtime.invoke("azure:lb/getBackendAddressPool:getBackendAddressPool", {
        "loadbalancerId": args.loadbalancerId,
        "name": args.name,
    }, opts);

    return kulado.utils.liftProperties(promise, opts);
}

/**
 * A collection of arguments for invoking getBackendAddressPool.
 */
export interface GetBackendAddressPoolArgs {
    /**
     * The ID of the Load Balancer in which the Backend Address Pool exists.
     */
    readonly loadbalancerId: string;
    /**
     * Specifies the name of the Backend Address Pool.
     */
    readonly name: string;
}

/**
 * A collection of values returned by getBackendAddressPool.
 */
export interface GetBackendAddressPoolResult {
    readonly loadbalancerId: string;
    readonly name: string;
    /**
     * id is the provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
}
