// *** WARNING: this file was generated by the Kulado Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as kulado from "@kulado/kulado";
import * as utilities from "../utilities";

/**
 * Manages an API Management Group.
 * 
 * 
 * ## Example Usage
 * 
 * ```typescript
 * import * as kulado from "@kulado/kulado";
 * import * as azure from "@kulado/azure";
 * 
 * const exampleResourceGroup = new azure.core.ResourceGroup("example", {
 *     location: "West US",
 *     name: "example-resources",
 * });
 * const exampleService = new azure.apimanagement.Service("example", {
 *     location: exampleResourceGroup.location,
 *     name: "example-apim",
 *     publisherEmail: "pub1@email.com",
 *     publisherName: "pub1",
 *     resourceGroupName: exampleResourceGroup.name,
 *     sku: {
 *         capacity: 1,
 *         name: "Developer",
 *     },
 * });
 * const exampleGroup = new azure.apimanagement.Group("example", {
 *     apiManagementName: exampleService.name,
 *     description: "This is an example API management group.",
 *     displayName: "Example Group",
 *     name: "example-apimg",
 *     resourceGroupName: exampleResourceGroup.name,
 * });
 * ```
 *
 * > This content is derived from https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/website/docs/r/api_management_group.html.markdown.
 */
export class Group extends kulado.CustomResource {
    /**
     * Get an existing Group resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     */
    public static get(name: string, id: kulado.Input<kulado.ID>, state?: GroupState, opts?: kulado.CustomResourceOptions): Group {
        return new Group(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __kuladoType = 'azure:apimanagement/group:Group';

    /**
     * Returns true if the given object is an instance of Group.  This is designed to work even
     * when multiple copies of the Kulado SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Group {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__kuladoType'] === Group.__kuladoType;
    }

    /**
     * The name of the API Management Service in which the API Management Group should exist. Changing this forces a new resource to be created.
     */
    public readonly apiManagementName!: kulado.Output<string>;
    /**
     * The description of this API Management Group.
     */
    public readonly description!: kulado.Output<string | undefined>;
    /**
     * The display name of this API Management Group.
     */
    public readonly displayName!: kulado.Output<string>;
    /**
     * The identifier of the external Group. For example, an Azure Active Directory group `aad://<tenant>.onmicrosoft.com/groups/<group object id>`.
     */
    public readonly externalId!: kulado.Output<string | undefined>;
    /**
     * The name of the API Management Group. Changing this forces a new resource to be created.
     */
    public readonly name!: kulado.Output<string>;
    /**
     * The name of the Resource Group in which the API Management Group should exist. Changing this forces a new resource to be created.
     */
    public readonly resourceGroupName!: kulado.Output<string>;
    /**
     * The type of this API Management Group. Possible values are `custom` and `external`. Default is `custom`.
     */
    public readonly type!: kulado.Output<string | undefined>;

    /**
     * Create a Group resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: GroupArgs, opts?: kulado.CustomResourceOptions)
    constructor(name: string, argsOrState?: GroupArgs | GroupState, opts?: kulado.CustomResourceOptions) {
        let inputs: kulado.Inputs = {};
        if (opts && opts.id) {
            const state = argsOrState as GroupState | undefined;
            inputs["apiManagementName"] = state ? state.apiManagementName : undefined;
            inputs["description"] = state ? state.description : undefined;
            inputs["displayName"] = state ? state.displayName : undefined;
            inputs["externalId"] = state ? state.externalId : undefined;
            inputs["name"] = state ? state.name : undefined;
            inputs["resourceGroupName"] = state ? state.resourceGroupName : undefined;
            inputs["type"] = state ? state.type : undefined;
        } else {
            const args = argsOrState as GroupArgs | undefined;
            if (!args || args.apiManagementName === undefined) {
                throw new Error("Missing required property 'apiManagementName'");
            }
            if (!args || args.displayName === undefined) {
                throw new Error("Missing required property 'displayName'");
            }
            if (!args || args.resourceGroupName === undefined) {
                throw new Error("Missing required property 'resourceGroupName'");
            }
            inputs["apiManagementName"] = args ? args.apiManagementName : undefined;
            inputs["description"] = args ? args.description : undefined;
            inputs["displayName"] = args ? args.displayName : undefined;
            inputs["externalId"] = args ? args.externalId : undefined;
            inputs["name"] = args ? args.name : undefined;
            inputs["resourceGroupName"] = args ? args.resourceGroupName : undefined;
            inputs["type"] = args ? args.type : undefined;
        }
        super(Group.__kuladoType, name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Group resources.
 */
export interface GroupState {
    /**
     * The name of the API Management Service in which the API Management Group should exist. Changing this forces a new resource to be created.
     */
    readonly apiManagementName?: kulado.Input<string>;
    /**
     * The description of this API Management Group.
     */
    readonly description?: kulado.Input<string>;
    /**
     * The display name of this API Management Group.
     */
    readonly displayName?: kulado.Input<string>;
    /**
     * The identifier of the external Group. For example, an Azure Active Directory group `aad://<tenant>.onmicrosoft.com/groups/<group object id>`.
     */
    readonly externalId?: kulado.Input<string>;
    /**
     * The name of the API Management Group. Changing this forces a new resource to be created.
     */
    readonly name?: kulado.Input<string>;
    /**
     * The name of the Resource Group in which the API Management Group should exist. Changing this forces a new resource to be created.
     */
    readonly resourceGroupName?: kulado.Input<string>;
    /**
     * The type of this API Management Group. Possible values are `custom` and `external`. Default is `custom`.
     */
    readonly type?: kulado.Input<string>;
}

/**
 * The set of arguments for constructing a Group resource.
 */
export interface GroupArgs {
    /**
     * The name of the API Management Service in which the API Management Group should exist. Changing this forces a new resource to be created.
     */
    readonly apiManagementName: kulado.Input<string>;
    /**
     * The description of this API Management Group.
     */
    readonly description?: kulado.Input<string>;
    /**
     * The display name of this API Management Group.
     */
    readonly displayName: kulado.Input<string>;
    /**
     * The identifier of the external Group. For example, an Azure Active Directory group `aad://<tenant>.onmicrosoft.com/groups/<group object id>`.
     */
    readonly externalId?: kulado.Input<string>;
    /**
     * The name of the API Management Group. Changing this forces a new resource to be created.
     */
    readonly name?: kulado.Input<string>;
    /**
     * The name of the Resource Group in which the API Management Group should exist. Changing this forces a new resource to be created.
     */
    readonly resourceGroupName: kulado.Input<string>;
    /**
     * The type of this API Management Group. Possible values are `custom` and `external`. Default is `custom`.
     */
    readonly type?: kulado.Input<string>;
}
