// *** WARNING: this file was generated by the Kulado Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as kulado from "@kulado/kulado";
import * as utilities from "../utilities";

/**
 * Associates a Route Table with a Subnet within a Virtual Network.
 * 
 * > **NOTE:** Subnet `<->` Route Table associations currently need to be configured on both this resource and using the `route_table_id` field on the `azurerm_subnet` resource. The next major version of the AzureRM Provider (2.0) will remove the `route_table_id` field from the `azurerm_subnet` resource such that this resource is used to link resources in future.
 * 
 * ## Example Usage
 * 
 * ```typescript
 * import * as kulado from "@kulado/kulado";
 * import * as azure from "@kulado/azure";
 * 
 * const testResourceGroup = new azure.core.ResourceGroup("test", {
 *     location: "West Europe",
 *     name: "example-resources",
 * });
 * const testRouteTable = new azure.network.RouteTable("test", {
 *     location: testResourceGroup.location,
 *     name: "example-routetable",
 *     resourceGroupName: testResourceGroup.name,
 *     routes: [{
 *         addressPrefix: "10.100.0.0/14",
 *         name: "example",
 *         nextHopInIpAddress: "10.10.1.1",
 *         nextHopType: "VirtualAppliance",
 *     }],
 * });
 * const testVirtualNetwork = new azure.network.VirtualNetwork("test", {
 *     addressSpaces: ["10.0.0.0/16"],
 *     location: testResourceGroup.location,
 *     name: "example-network",
 *     resourceGroupName: testResourceGroup.name,
 * });
 * const testSubnet = new azure.network.Subnet("test", {
 *     addressPrefix: "10.0.2.0/24",
 *     name: "frontend",
 *     resourceGroupName: testResourceGroup.name,
 *     routeTableId: testRouteTable.id,
 *     virtualNetworkName: testVirtualNetwork.name,
 * });
 * const testSubnetRouteTableAssociation = new azure.network.SubnetRouteTableAssociation("test", {
 *     routeTableId: testRouteTable.id,
 *     subnetId: testSubnet.id,
 * });
 * ```
 *
 * > This content is derived from https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/website/docs/r/subnet_route_table_association.html.markdown.
 */
export class SubnetRouteTableAssociation extends kulado.CustomResource {
    /**
     * Get an existing SubnetRouteTableAssociation resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     */
    public static get(name: string, id: kulado.Input<kulado.ID>, state?: SubnetRouteTableAssociationState, opts?: kulado.CustomResourceOptions): SubnetRouteTableAssociation {
        return new SubnetRouteTableAssociation(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __kuladoType = 'azure:network/subnetRouteTableAssociation:SubnetRouteTableAssociation';

    /**
     * Returns true if the given object is an instance of SubnetRouteTableAssociation.  This is designed to work even
     * when multiple copies of the Kulado SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is SubnetRouteTableAssociation {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__kuladoType'] === SubnetRouteTableAssociation.__kuladoType;
    }

    /**
     * The ID of the Route Table which should be associated with the Subnet. Changing this forces a new resource to be created.
     */
    public readonly routeTableId!: kulado.Output<string>;
    /**
     * The ID of the Subnet. Changing this forces a new resource to be created.
     */
    public readonly subnetId!: kulado.Output<string>;

    /**
     * Create a SubnetRouteTableAssociation resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: SubnetRouteTableAssociationArgs, opts?: kulado.CustomResourceOptions)
    constructor(name: string, argsOrState?: SubnetRouteTableAssociationArgs | SubnetRouteTableAssociationState, opts?: kulado.CustomResourceOptions) {
        let inputs: kulado.Inputs = {};
        if (opts && opts.id) {
            const state = argsOrState as SubnetRouteTableAssociationState | undefined;
            inputs["routeTableId"] = state ? state.routeTableId : undefined;
            inputs["subnetId"] = state ? state.subnetId : undefined;
        } else {
            const args = argsOrState as SubnetRouteTableAssociationArgs | undefined;
            if (!args || args.routeTableId === undefined) {
                throw new Error("Missing required property 'routeTableId'");
            }
            if (!args || args.subnetId === undefined) {
                throw new Error("Missing required property 'subnetId'");
            }
            inputs["routeTableId"] = args ? args.routeTableId : undefined;
            inputs["subnetId"] = args ? args.subnetId : undefined;
        }
        super(SubnetRouteTableAssociation.__kuladoType, name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering SubnetRouteTableAssociation resources.
 */
export interface SubnetRouteTableAssociationState {
    /**
     * The ID of the Route Table which should be associated with the Subnet. Changing this forces a new resource to be created.
     */
    readonly routeTableId?: kulado.Input<string>;
    /**
     * The ID of the Subnet. Changing this forces a new resource to be created.
     */
    readonly subnetId?: kulado.Input<string>;
}

/**
 * The set of arguments for constructing a SubnetRouteTableAssociation resource.
 */
export interface SubnetRouteTableAssociationArgs {
    /**
     * The ID of the Route Table which should be associated with the Subnet. Changing this forces a new resource to be created.
     */
    readonly routeTableId: kulado.Input<string>;
    /**
     * The ID of the Subnet. Changing this forces a new resource to be created.
     */
    readonly subnetId: kulado.Input<string>;
}
